### ISSUE TITLE
src/Main.cpp:123:14: error: ‘struct projectM::Settings’ has no member named ‘datadir’

### ISSUE THREAD

**Issue by candrews** [xbmc/visualization.projectm#25]
Following the direction in README.md and using current master 59bba2, I'm getting a build failure.

I'm running Gentoo Linux (I'm trying to package this addon for Gentoo users), have projectm-3.1.0 installed, and I'm using Kodi master bc4995.

I'm getting this error:
```
/var/tmp/portage/media-plugins/kodi-visualization-projectm-9999/work/kodi-visualization-projectm-9999/src/Main.cpp: In constructor ‘CVisualizationProjectM::CVisualizationProjectM()’:
/var/tmp/portage/media-plugins/kodi-visualization-projectm-9999/work/kodi-visualization-projectm-9999/src/Main.cpp:123:14: error: ‘struct projectM::Settings’ has no member named ‘datadir’
   m_configPM.datadir = kodi::GetAddonPath() + "/resources/projectM";
```

Here's CMakeCache.txt: https://pastebin.com/8jQ0Z1Ly
And the full build output: https://pastebin.com/pbG3Vt8S

Also, I noticed that there is a  .travis.yml in this directory, but Travis doesn't seem to be hooked up, see https://travis-ci.org/notspiff/visualization.projectm

**Comment by notspiff** [comment]
Apply the patch.

Den man. 5. nov. 2018, 16:47 skrev Craig Andrews <notifications@github.com:

**Comment by wsnipex** [comment]
or use projectm master

**Comment by Rechi** [comment]
You either have to build projectm with  [01-datadir.patch](https://github.com/xbmc/visualization.projectm/blob/b549160/depends/common/projectm/01-datadir.patch) or patch away the one line. The change is already accepted upstream, but not in a released version yet.

Correct travis project is https://travis-ci.org/xbmc/visualization.projectm which is working correctly.

**Comment by candrews** [comment]
Thanks for the explanation of the issue, the patch fixing, and for fixing the README.md / Travis reference :+1:
