### ISSUE TITLE
cannot find "/usr/share/projectM"

### ISSUE THREAD

**Issue by CvH** [xbmc/visualization.projectm#26]
Since b54916007227d49131f7cc4d111d18e6a94c8dd0 building fails with
```
-- Up-to-date: /LE/build.LibreELEC-Generic.x86_64/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/share/kodi/addons/visualization.projectm/resources/settings.xml
-- Up-to-date: /LE/build.LibreELEC-Generic.x86_64/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/share/kodi/addons/visualization.projectm
-- Installing: /LE/build.LibreELEC-Generic.x86_64/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/share/kodi/addons/visualization.projectm/addon.xml
CMake Error at cmake_install.cmake:125 (file):
  file INSTALL cannot find "/usr/share/projectM".


FAILED: CMakeFiles/install.util 
cd /LE/build.LibreELEC-Generic.x86_64/visualization.projectm-b54916007227d49131f7cc4d111d18e6a94c8dd0/.x86_64-libreelec-linux-gnu && /LE/build.LibreELEC-Generic.x86_64/toolchain/bin/cmake -P cmake_install.cmake
ninja: build stopped: subcommand failed.
```

Could anyone point us (we are no cmake magicians) what we are missing here? We are building visualization.projectm like every other visualization.... addon and it worked before without any problem.
Currently we are unsure if this is an bug or an feature.

**Comment by Rechi** [comment]
What projectM version are you using?

**Comment by Rechi** [comment]
Looks like the prefix directory in the projectM pkg config file is wrong, /usr instead of wherever your path to the LE root directory during building is.

**Comment by wsnipex** [comment]
don't expect projectm's build system to ever "just work" ;)

**Comment by CvH** [comment]
hmm I found an "solution"
If I manually replace `${PROJECTM_PREFIX}` at https://github.com/xbmc/visualization.projectm/blob/master/FindProjectM.cmake#L39 with the LE sysroot path it works. But I was not able to do it via `-DPROJECTM_PREFIX=1234` nor export of the value etc. Is this variable somewhere overwritten with `/usr` ?

**Comment by Rechi** [comment]
In cmakes built-in function/macro `pkg_check_modules`, because of the wrong pkg file.

**Comment by CvH** [comment]
`because of the wrong pkg file` sorry I can't follow :)
Normally I could overwrite the cmake values with `-DPROJECTM_PREFIX=1234` if something is not found etc. This time cmake ignores it and sets `/usr` regardless. I am just a bit surprised that it works for this addon differently as for every other Kodi addon. 

Maybe to shorten the QA, I am still not really understood at what point I made the mistake btw what I need to set that it overwrites `$PROJECTM_PREFIX` ? (like said cmake noob here)

**Comment by Rechi** [comment]
I've no idea as it's nothing the cmake files of this repo do, it's the `pkg_check_modules` macro implemented in cmake core (https://github.com/Kitware/CMake/blob/master/Modules/FindPkgConfig.cmake).
From looking quickly at that macro it is expected that `PROJECTM_PREFIX` can't be overwritten.

**Comment by CvH** [comment]
@Rechi tx for explanation, so still no idea how to proper fix it or why this addon behaves differently to every other kodi addon -> I fix it with some patch.

**Comment by wsnipex** [comment]
for reference though. The FindProjectm module could also be enhanced to not only rely on pkgconfig, which would likely fix the issue as well.

**Comment by AlwinEsch** [comment]
Possible that problem is fixed with https://github.com/xbmc/visualization.projectm/pull/38, can you confirm it?

**Comment by revmischa** [comment]
Please feel free to submit PRs upstream to projectM's build system if it's lacking. We could use some more help

**Comment by AlwinEsch** [comment]
Think this issue no more needed.
