### ISSUE TITLE
PPA version not installable

### ISSUE THREAD

**Issue by Jalle19** [xbmc/visualization.projectm#28]
```
$ sudo apt install kodi-visualization-projectm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kodi-visualization-projectm : Depends: libprojectm3 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by Jalle19** [comment]
@wsnipex is this something you could fix? Or is there a PPA for libprojectm3 somewhere that I haven't been able to find?

**Comment by wsnipex** [comment]
$ apt policy libprojectm3 
libprojectm3:
  Installed: 3.1.0-4~bionic
  Candidate: 3.1.0-4~bionic
  Version table:
 *** 3.1.0-4~bionic 500
        500 http://ppa.launchpad.net/team-xbmc/xbmc-nightly/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by wsnipex** [comment]
ok, libprojectm3 was missing for in the unstable ppa for ubuntu 16,04 and 18.04.
They are being published there right now

**Comment by Jalle19** [comment]
Thanks, installed and working!
