### ISSUE TITLE
[Question] Where to put textures...

### ISSUE THREAD

**Issue by tonyschuite** [xbmc/visualization.projectm#4]
Hi There, 

I am a Happy user of projectM for ages. However I am trying out some new presets. They come with a textures folder supplied. Where do I put the textures?

it is a pretty well known pack from http://ghostco.de/milkdrop_pack/ called tryptonaut

**Comment by notspiff** [comment]
hi there. sorry for delayed answer, so much to do, so little time ;)
first, to avoid confusion: you do understand this is the kodi add-on for projectm, not projectm itself.

i really cannot answer your question based on so little information. which platform?  is the add-on using system projectm or static linked against libprojectM?

last time i checked, libprojectM would not allow me to configure the texture directory used, only the preset directory. it will always read from <install_prefix>/share/projectM/textures.

**Comment by revmischa** [comment]
All of the tryptonaut textures and presets should come with the new projectM... shader support (which handles the textures) is being readded presently https://github.com/projectM-visualizer/projectm/pull/26

**Comment by AlwinEsch** [comment]
Think this is largely possible, within the addon settings, a separate folder could be selected to use related * .milk files.

In addition, there is a change to select the presets installed on the addon by type.
